[package]
name = "graf"
version = "0.1.0"
edition = "2021"

authors = ["shua <itis@isthisa.email>"]

[dependencies]
libc = "0.2.140"
serde_json = { version = "1.0.94", features = ["raw_value"] }

[profile.release]
opt-level = 3
lto = true
